# Generated by Django 5.2 on 2025-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_rolusuario_usuario_delete_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_generico', max_length=150, unique=True),
        ),
    ]
