# Generated by Django 5.2 on 2025-04-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
