# Generated by Django 5.2 on 2025-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hostilidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
    ]
