# Generated by Django 5.2 on 2025-04-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(upload_to='animales/'),
        ),
    ]
