# Generated by Django 5.2 on 2025-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_arma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
