# Generated by Django 5.2 on 2025-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_arma_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
